# Generated by Django 3.1.4 on 2020-12-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, unique=True, verbose_name='Email')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('grau', models.CharField(choices=[('1', 'Superior'), ('2', 'Técnico')], max_length=1, verbose_name='Estudando do Ensino ?')),
                ('curso', models.CharField(choices=[('1', 'Análise e Desenvolvimento de Sistemas - ADS'), ('2', 'Engenharia Agronômica'), ('3', 'Tecnologia em Processos Gerenciais'), ('4', 'Técnico em Administração Integrado ao Ensino Médio'), ('5', 'Técnico em Agropecuária Integrado ao Ensino Médio'), ('6', 'Técnico Agropecuária Integrado ao Ensino Médio em Regime de Alternância'), ('7', 'Técnico em Informática Integrado ao Ensino Médio'), ('8', 'Técnico em Zootecnia Integrado ao Ensino Médio'), ('9', 'Técnico em Enfermagem Subsequente')], max_length=1, verbose_name='Qual é o seu curso?')),
                ('turma', models.CharField(choices=[('1', '0120'), ('2', '0119'), ('3', '0118'), ('4', '0117'), ('5', '0116'), ('6', '0115'), ('7', '0114')], max_length=1, verbose_name='Qual a sua Turma?')),
                ('pergunta1', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Responda 1 para Péssimo e 5 para Ótimo', max_length=1, verbose_name="Como as ANP's contribuíram para o seu aprendizado?")),
                ('pergunta2', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Responda 1 para Péssimo e 5 para Ótimo', max_length=1, verbose_name='Em seu ponto de vista,o formato de aula remota que o IFNMG propôs gera conexão entre aluno e o instituto?')),
                ('pergunta3', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Responda 1 para Péssimo e 5 para Ótimo', max_length=1, verbose_name='Em seu ponto de vista,as aulas remotas foram importantes e efetivas?')),
                ('pergunta4', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Responda 1 para Péssimo e 5 para Ótimo', max_length=1, verbose_name='Avalie sua satisfação em relação às atividades remotas?')),
                ('pergunta5', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Responda 1 para Péssimo e 5 para Ótimo', max_length=1, verbose_name='Você acredita que os meios de comunicação usados pelo IFNMG neste momento de distanciamento social para compartilhar informações gerais foram eficientes?')),
                ('pergunta6', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Responda 1 para Péssimo e 5 para Ótimo', max_length=1, verbose_name='Como você classifica o conteúdo e o tipo de material que está estudando?')),
                ('pergunta7', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Responda 1 para Péssimo e 5 para Ótimo', max_length=1, verbose_name='Qual a maior dificuldade que você tem em estudar a distância?')),
                ('pergunta8', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Responda 1 para Péssimo e 5 para Ótimo', max_length=1, verbose_name='Quantas horas no mínimo você estuda o material disponibilizado para o seu curso?')),
                ('pergunta9', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Responda 1 para Péssimo e 5 para Ótimo', max_length=1, verbose_name='pergunta        9')),
            ],
        ),
    ]
